import type { SportSlug } from './sport-landing';

type Editorial = {
  headline: string; intro: string; registration: string; scheduling: string;
  tournaments: string; details: string[]; question: string; answer: string;
};

// Handwritten sport-specific workflows. Describe coordination tools, not specialized scoring engines.
export const SPORT_EDITORIAL: Record<SportSlug, Editorial> = {
  soccer: {
    headline: 'Less chasing replies. More time on the pitch.',
    intro: 'Bring field changes, match availability, and family updates into the same workspace—from the first training session to the last whistle.',
    registration: 'Collect age-group details, coach contacts, player registrations, and waivers before the first fixture.',
    scheduling: 'Assign pitches to training and matches. Keep local kickoff times and field changes attached to the event families already follow.',
    tournaments: 'Coordinate pools, knockout rounds, officials, and spectator schedules across your available fields.',
    details: ['Pitch and kickoff coordination', 'Age-group registration', 'Match-day scorer preparation'],
    question: 'Can I keep a paper record at the touchline?',
    answer: 'Yes. Download the soccer pack below for goals, cards, substitutions, and separate shootout records. Confirm your competition’s requirements before using it.',
  },
  basketball: {
    headline: 'One team workspace. Every court covered.',
    intro: 'Keep gym changes, game availability, and tournament weekends out of scattered group messages and alongside your roster.',
    registration: 'Organize player and team registration by age group or division, with coach contacts and signed waivers.',
    scheduling: 'Give practices and games a clear gym, court, date, and start time. Share changes with the people attending.',
    tournaments: 'Plan court assignments, pool games, brackets, and officials while publishing a separate spectator schedule.',
    details: ['Gym and court assignments', 'Division registration', 'Scorer-table preparation'],
    question: 'Is the basketball worksheet for 5-on-5 or 3x3?',
    answer: 'The downloadable pack is for standard 5-on-5 basketball. It tracks scoring events, fouls, and timeouts; it is not a 3x3 sheet.',
  },
  baseball: {
    headline: 'Get the lineup ready. Keep the season moving.',
    intro: 'Coordinate diamond time, player availability, and tournament travel without losing track of the next game.',
    registration: 'Collect player details, division information, coach contacts, and waivers before building the team roster.',
    scheduling: 'Assign diamonds to games and practices, and publish location or start-time changes from the team schedule.',
    tournaments: 'Keep participating teams, diamond assignments, officials, and bracket schedules connected during busy tournament weekends.',
    details: ['Diamond assignments', 'Pre-game availability', 'Printable inning records'],
    question: 'What does the baseball scorebook include?',
    answer: 'The pack provides batting records, runner-advancement diamonds, inning totals, and continuation space. Use one batting sheet per team and extra sheets when needed.',
  },
  rugby: {
    headline: 'Bring the club together before kickoff.',
    intro: 'Connect training groups, pitch locations, match availability, and club communication without handing every member staff access.',
    registration: 'Collect squad, age-group, emergency-contact, and waiver information through your configured registration form.',
    scheduling: 'Plan training and fixtures with pitch locations, local kickoff times, and attendance in one shared calendar.',
    tournaments: 'Organize club competitions through team registration, venue assignments, schedules, and public event information.',
    details: ['Club and age-group coordination', 'Training-pitch logistics', 'Away-match updates'],
    question: 'Can coaches share match information without exposing private records?',
    answer: 'Use team communication for squad updates and the competition’s public spectator view for published schedules. Private roster information remains subject to role permissions.',
  },
  football: {
    headline: 'Build a game-day plan everyone can follow.',
    intro: 'Keep practice locations, team availability, volunteer roles, and kickoff details organized before the sideline gets busy.',
    registration: 'Collect player and team information, division details, waivers, and guardian contacts where applicable.',
    scheduling: 'Coordinate practice fields and game venues with local start times, attendance, and updates for the squad.',
    tournaments: 'Organize participating teams, fixtures, facilities, officials, and spectator-facing competition information.',
    details: ['Practice-field coordination', 'Game-day volunteer roles', 'American-football scoring worksheets'],
    question: 'Does the printable sheet cover Canadian football?',
    answer: 'The current downloadable pack uses American-football scoring. It does not include the Canadian single; use the appropriate official or local worksheet for that format.',
  },
  cornhole: {
    headline: 'From league night to the final bag.',
    intro: 'Keep doubles partners, venue details, match schedules, and tournament communication organized around your boards.',
    registration: 'Collect player or team entries, partner information, and division details in configurable forms.',
    scheduling: 'Plan league nights and matches with a clear venue, start time, and assigned playing area.',
    tournaments: 'Coordinate entries, brackets, playing spaces, and spectator schedules from a shared event workspace.',
    details: ['Partner and team entries', 'Board-area coordination', 'Round-by-round paper scoring'],
    question: 'Which scoring format does the cornhole pack use?',
    answer: 'It uses cancellation scoring and includes a guide. Check the event’s rules before play; the included format is not an exact-21 or bust variant.',
  },
  gymnastics: {
    headline: 'Keep every training group in the loop.',
    intro: 'Make session locations, attendance, coach updates, and family communication easier to follow throughout the training season.',
    registration: 'Collect participant details, training-group information, guardian contacts, and required waivers.',
    scheduling: 'Publish training sessions, facility locations, and showcase dates with attendance connected to each event.',
    tournaments: 'Coordinate meet or showcase logistics, participant information, volunteers, and published schedules. Use your governing body’s system for official judging.',
    details: ['Training-group registration', 'Session attendance', 'Meet and showcase logistics'],
    question: 'Does The Squad replace an official gymnastics judging system?',
    answer: 'No. This page describes registration, scheduling, communication, and event coordination. Official apparatus judging and results requirements should be handled with the tools mandated by your competition.',
  },
  pickleball: {
    headline: 'Keep your court community connected.',
    intro: 'Bring session details, player entries, court locations, and event updates together for club nights and tournament days.',
    registration: 'Collect singles or doubles entries, partner details, and organizer-defined divisions with configurable forms.',
    scheduling: 'Assign facilities and courts to scheduled sessions or matches. Share the same location and start-time updates with players.',
    tournaments: 'Organize entries, matches, court assignments, brackets, and public schedules for your event format.',
    details: ['Singles and doubles entries', 'Court and session coordination', 'Side-out scoring worksheets'],
    question: 'Does the printable pack use rally scoring?',
    answer: 'No. The current pickleball pack uses traditional side-out scoring. Choose a worksheet matching your event if it uses rally scoring instead.',
  },
  tennis: {
    headline: 'A clearer plan for every court session.',
    intro: 'Coordinate players, clinics, match locations, and club updates without making families search multiple conversations.',
    registration: 'Collect participant or team entries, contact information, and organizer-defined groups for clinics and competitions.',
    scheduling: 'Publish lesson, practice, and match events with court locations, local times, and attendance.',
    tournaments: 'Coordinate entries, match schedules, court assignments, and spectator information. Record your competition’s format before play.',
    details: ['Clinic and player registration', 'Court assignments', 'Set and tie-break worksheets'],
    question: 'Can the paper sheet record a deciding match tie-break?',
    answer: 'The tennis pack keeps set games and tie-break points separate. Enter the event’s deciding-set or match tie-break format before scoring.',
  },
  golf: {
    headline: 'Organize the day before the first tee.',
    intro: 'Keep event entries, meeting points, volunteer assignments, and player updates together for your next club outing.',
    registration: 'Collect player entries, division information, contacts, and event-specific answers before the registration deadline.',
    scheduling: 'Publish round events, course locations, meeting times, and organizer-provided instructions. This is event coordination, not a live course inventory booking system.',
    tournaments: 'Coordinate player registration, divisions, volunteers, and event schedules alongside the scoring process required by your club.',
    details: ['Player and event entries', 'Course and meeting-point details', 'Stroke-play paper records'],
    question: 'Which golf format does the downloadable card support?',
    answer: 'The current card is for stroke play, with gross strokes and separate handicap/net totals. It is not a Stableford or match-play card.',
  },
  swimming: {
    headline: 'Keep poolside plans clear for every family.',
    intro: 'Bring training times, pool locations, attendance, and meet-day instructions into one connected team workspace.',
    registration: 'Collect swimmer details, training-group information, emergency contacts, and required waivers.',
    scheduling: 'Plan sessions and meet events with facility locations, attendance, and coach-provided lane or arrival instructions.',
    tournaments: 'Coordinate meet logistics, volunteers, and team communication while retaining your official timing and meet-management system.',
    details: ['Training-group coordination', 'Pool and arrival instructions', 'Meet-day volunteers'],
    question: 'Does The Squad replace electronic swimming timing?',
    answer: 'No. Use The Squad for registration, schedules, attendance, and communication. Official timing, heat seeding, and certified results remain with your meet’s designated system.',
  },
  esports: {
    headline: 'Keep the team ready when the lobby opens.',
    intro: 'Coordinate practice sessions, match times, roster access, and competition updates across your team’s local time zones.',
    registration: 'Collect team entries, player contacts, and game-specific information through organizer-configured registration questions.',
    scheduling: 'Publish scrims, practice sessions, and competition matches with local times and joining instructions in event notes.',
    tournaments: 'Organize teams, brackets, match schedules, and public event information. Record results through the event’s supported scoring workflow.',
    details: ['Team and player entries', 'Local-time match schedules', 'Scrim and event communication'],
    question: 'Are game servers or anti-cheat tools included?',
    answer: 'No. The Squad coordinates team and event operations; your chosen game platform provides servers, lobby access, and anti-cheat controls.',
  },
  'ultimate-frisbee': {
    headline: 'Spend less time coordinating. More time playing.',
    intro: 'Bring field allocations, squad availability, travel instructions, and tournament updates together for your ultimate community.',
    registration: 'Collect player or team entries, divisions, contacts, and waivers for the club season or event.',
    scheduling: 'Assign fields to practices and games, track attendance, and share changes with the team.',
    tournaments: 'Coordinate team registration, fields, brackets, and public schedules. Share spirit expectations and competition rules in event information.',
    details: ['Field and team coordination', 'Tournament travel details', 'Published competition instructions'],
    question: 'Can organizers share spirit-of-the-game expectations?',
    answer: 'Yes. Use event descriptions, team communication, and shared files for your competition’s expectations. Dedicated spirit-score adjudication is not promised by this page.',
  },
  'disc-golf': {
    headline: 'Bring the league together beyond the first basket.',
    intro: 'Make course locations, round times, divisions, and player updates easy to find before a league round or club event.',
    registration: 'Collect player entries, organizer-defined divisions, contact details, and event-specific registration answers.',
    scheduling: 'Publish round times, course locations, and meeting instructions with updates linked to the event.',
    tournaments: 'Coordinate entries, divisions, volunteers, and event schedules alongside the official scoring service chosen by the organizer.',
    details: ['Player and division entries', 'Course meeting instructions', 'Round and volunteer coordination'],
    question: 'Is a dedicated disc-golf scorecard available here?',
    answer: 'Not yet. Browse the available branded packs below, but do not substitute the ball-golf stroke-play sheet for a competition-required disc-golf card.',
  },
  hockey: {
    headline: 'Make every minute of ice time count.',
    intro: 'Keep rink changes, player availability, and bench communication together through practices, league games, and tournament weekends.',
    registration: 'Collect player and team details, age divisions, coach contacts, and waivers before the first skate.',
    scheduling: 'Assign rink locations and start times to practices and games. Keep arrival instructions and attendance alongside the event.',
    tournaments: 'Coordinate teams, ice surfaces, officials, brackets, and spectator schedules across a tournament weekend.',
    details: ['Ice-surface assignments', 'Bench and arrival instructions', 'Goal and penalty worksheets'],
    question: 'Can the scorer keep shootout attempts separate?',
    answer: 'Yes. The hockey pack distinguishes shootout attempts from regulation and overtime goals. Apply your competition’s final-score convention.',
  },
  'slo-pitch': {
    headline: 'Your league night, without the last-minute scramble.',
    intro: 'Keep diamond locations, player replies, batting-order preparation, and weekend tournament details in one place.',
    registration: 'Collect team entries, player contacts, divisions, and organizer-defined roster information.',
    scheduling: 'Publish league games and practices with diamond assignments, local start times, and attendance.',
    tournaments: 'Coordinate team registration, diamond schedules, brackets, and volunteer assignments for multi-game weekends.',
    details: ['League-night attendance', 'Diamond and team coordination', 'Slo-pitch batting records'],
    question: 'Can the scoresheet accommodate local run caps?',
    answer: 'Enter your league’s run caps, home-run limits, courtesy-runner rules, and tie-break format before play. The guide explicitly calls out local variations.',
  },
  softball: {
    headline: 'Keep the whole squad ready for the next pitch.',
    intro: 'Bring player registration, diamond time, team availability, and travel updates together throughout your softball season.',
    registration: 'Collect player details, divisions, coach contacts, guardian information where needed, and required waivers.',
    scheduling: 'Coordinate diamonds for practices and games, with clear locations, local times, and attendance.',
    tournaments: 'Organize participating teams, facilities, officials, brackets, and spectator schedules for your chosen format.',
    details: ['Player and division registration', 'Diamond and travel logistics', 'Team availability'],
    question: 'Is the slo-pitch pack also an official fastpitch sheet?',
    answer: 'No. The available slo-pitch pack is labeled for that format. Fastpitch organizers should use a worksheet matching their competition’s requirements; a dedicated fastpitch pack is not included yet.',
  },
  volleyball: {
    headline: 'Bring the team together from first serve to match point.',
    intro: 'Keep gym locations, court assignments, match availability, and tournament updates connected for coaches and families.',
    registration: 'Collect team entries, player details, divisions, coach contacts, and waivers for your indoor program.',
    scheduling: 'Assign courts to training and matches, and share arrival times, venue instructions, and changes.',
    tournaments: 'Coordinate pool play, brackets, court assignments, officials, and spectator schedules across the venue.',
    details: ['Indoor court assignments', 'Team and division entries', 'Set-by-set scoring worksheets'],
    question: 'Is this scoresheet suitable for beach volleyball?',
    answer: 'The current pack is for indoor volleyball. It records sets separately and includes a local-format note; use the required beach-specific form for beach competitions.',
  },
  'field-lacrosse': {
    headline: 'Keep field days focused on the game.',
    intro: 'Coordinate practice fields, player availability, coach updates, and competition weekends from the same team workspace.',
    registration: 'Collect player and team entries, divisions, contact details, and waivers for your field program.',
    scheduling: 'Assign outdoor fields and local start times, with attendance and arrival instructions connected to each event.',
    tournaments: 'Organize team registration, fields, officials, brackets, and spectator information across the competition.',
    details: ['Outdoor field assignments', 'Team and family updates', 'Field-specific scorer records'],
    question: 'Does the pack distinguish field from box lacrosse?',
    answer: 'Yes. Separate packs are available. For field play, specify the applicable men’s or women’s rules and period lengths before recording goals, penalties or cards, and goalkeeper information.',
  },
  'box-lacrosse': {
    headline: 'Get the bench ready before the arena fills.',
    intro: 'Keep arena assignments, roster availability, arrival instructions, and tournament communication organized around your box team.',
    registration: 'Collect player entries, divisions, coach contacts, and required waivers before the indoor season.',
    scheduling: 'Coordinate arena floors, practice sessions, and game times with attendance and shared venue instructions.',
    tournaments: 'Organize entries, arena assignments, officials, brackets, and spectator schedules through the competition hub.',
    details: ['Arena-floor coordination', 'Bench and roster preparation', 'Box-specific goal and penalty records'],
    question: 'What if our box league uses three periods?',
    answer: 'The box pack starts with four quarters for World Lacrosse box play. Its guide explains how to relabel the columns for domestic three-period formats before the game.',
  },
};
