import assert from 'node:assert/strict';
import test from 'node:test';
import {build} from 'esbuild';
import {Webhook} from 'svix';
import {communicationDb} from './helpers/communication-route-harness.mjs';
const secret='whsec_'+Buffer.from('local-offline-signature-fixture-only').toString('base64');
async function load(initial={}){const {db,records}=communicationDb(initial);const proto=Object.getPrototypeOf(db.doc('fixture/path')),set=proto.set;proto.set=function(v,o){return o?.merge&&records.has(this.path)?this.update(v):set.call(this,v)};db.batch=()=>{const writes=[];return{set:(r,v,o)=>writes.push(()=>r.set(v,o)),async commit(){for(const w of writes)await w()}}};const key='resend_local_'+Math.random();globalThis[key]=db;const stubs={'next/server':`export class NextResponse extends Response {static json(v,i={}){return new NextResponse(JSON.stringify(v),i)}}`,'@/lib/firebase-admin':`export const adminDb=globalThis[${JSON.stringify(key)}]`,'firebase-admin/firestore':`export const FieldValue={increment:v=>({__increment:v}),delete:()=>({__delete:true}),serverTimestamp:()=>({__serverTimestamp:true}),arrayUnion:(...v)=>({__arrayUnion:v})}`};const b=await build({entryPoints:[new URL('../src/app/api/webhooks/resend/route.ts',import.meta.url).pathname],bundle:true,platform:'node',format:'esm',write:false,logLevel:'silent',plugins:[{name:'local-db',setup(x){x.onResolve({filter:/.*/},a=>Object.hasOwn(stubs,a.path)?{path:a.path,namespace:'fixture'}:null);x.onLoad({filter:/.*/,namespace:'fixture'},a=>({contents:stubs[a.path],loader:'js'}))}}]});const old=[process.env.RESEND_WEBHOOK_SECRET,process.env.RESEND_API_KEY];process.env.RESEND_WEBHOOK_SECRET=secret;process.env.RESEND_API_KEY='re_local_fixture_not_a_credential';const route=await import('data:text/javascript;base64,'+Buffer.from(b.outputFiles[0].text).toString('base64'));return{route,records,dispose(){delete globalThis[key];for(const[i,k]of ['RESEND_WEBHOOK_SECRET','RESEND_API_KEY'].entries()){if(old[i]===undefined)delete process.env[k];else process.env[k]=old[i]}}}}
function request(event,id='local_delivery_001',bad=false){const payload=JSON.stringify(event),time=new Date(),signature=new Webhook(secret).sign(id,time,payload);return new Request('http://127.0.0.1/api/webhooks/resend',{method:'POST',headers:{'svix-id':id,'svix-timestamp':String(Math.floor(time.getTime()/1000)),'svix-signature':bad?'v1,invalid':signature},body:payload})}
const event={type:'email.delivered',created_at:'2026-10-05T00:00:00.000Z',data:{email_id:'local_email_001',to:['local@local.test'],broadcast_id:'local_broadcast'}};
test('actual Resend handler verifies official offline signatures and rejects forgery before writes',async()=>{const h=await load();try{assert.equal((await h.route.POST(request(event,'invalid_delivery',true))).status,400);assert.equal(h.records.size,0);const missing=new Request('http://127.0.0.1/api/webhooks/resend',{method:'POST',body:'{}'});assert.equal((await h.route.POST(missing)).status,400);assert.equal(h.records.size,0)}finally{h.dispose()}});
test('actual Resend handler deduplicates signed delivery and preserves terminal contact status against delayed events',async()=>{const h=await load({'newsletter_campaigns/local':{resendBroadcastId:'local_broadcast',deliveredCount:0},'contact_inquiries/local':{resendEmailId:'local_email_001',deliveryStatus:'accepted'}});try{assert.equal((await h.route.POST(request(event))).status,200);assert.equal(h.records.get('newsletter_campaigns/local').deliveredCount,1);assert.equal(h.records.get('contact_inquiries/local').deliveryStatus,'delivered');const replay=await h.route.POST(request(event));assert.equal((await replay.json()).duplicate,true);assert.equal(h.records.get('newsletter_campaigns/local').deliveredCount,1);assert.equal((await h.route.POST(request({...event,type:'email.delivery_delayed'},'local_delivery_002'))).status,200);assert.equal(h.records.get('contact_inquiries/local').deliveryStatus,'delivered');assert.equal([...h.records.values()].filter(v=>v.deliveryId).length,2)}finally{h.dispose()}});
test('actual Resend handler suppresses only owned subscriber fixtures after a verified permanent bounce',async()=>{const h=await load({'newsletter_subscribers/local':{email:'local@local.test',isActive:true},'newsletter_subscribers/companion':{email:'companion@local.test',isActive:true}});try{assert.equal((await h.route.POST(request({...event,type:'email.bounced'},'local_bounce_001'))).status,200);assert.equal(h.records.get('newsletter_subscribers/local').isActive,false);assert.equal(h.records.get('newsletter_subscribers/local').suppressionReason,'email.bounced');assert.equal(h.records.get('newsletter_subscribers/companion').isActive,true)}finally{h.dispose()}});
