import assert from 'node:assert/strict';
import test from 'node:test';
import {build} from 'esbuild';
import {communicationDb} from './helpers/communication-route-harness.mjs';
async function load(routePath, initial, auth={uid:'owner'}, access={allowed:true}){
 const {db,records}=communicationDb(initial);let calls=0;
 const collection=db.collection.bind(db);db.collection=path=>{const q=collection(path);const doc=q.doc.bind(q);q.doc=id=>{const ref=doc(id),nested=ref.collection.bind(ref);ref.collection=name=>{const n=nested(name);n.add=async value=>{const r=n.doc();await r.create(value);return r};return n};return ref};return q};
 const key='safe_finance_'+Math.random();globalThis[key]={db,auth,access};const stubs={
 'next/server':`export class NextResponse extends Response {static json(v,i={}){return new NextResponse(JSON.stringify(v),i)}}`,
 '@/lib/firebase-admin':`export const adminDb=globalThis[${JSON.stringify(key)}].db;`,
 '@/lib/api-auth':`export async function verifyFirebaseToken(){return globalThis[${JSON.stringify(key)}].auth} export function assertNonAnonymous(a){return a.isAnonymous?new Response('{}',{status:401}):null}`,
 '@/lib/server-team-entitlements':`export async function getTeamFinanceAccess(){return globalThis[${JSON.stringify(key)}].access}`,
 '@/lib/server-request-guards':`export class RequestBodyError extends Error {} export async function enforcePublicRateLimit(){return null} export async function enforceUserRateLimit(){return null} export async function readJsonBodyWithLimit(r){return r.json()}`,
 '@/lib/stripe-client':`export function getStripe(){throw Error('Provider access forbidden in local projections tests')}`,
 '@/lib/server-stripe-connect':`export async function resolveTeamConnectAccount(){throw Error('Provider access forbidden')}`,
 '@/lib/store-request-guard':`export function storePurchaseResponse(){return null}`,
 };
 const output=await build({entryPoints:[new URL('../src/app/api/'+routePath+'/route.ts',import.meta.url).pathname],bundle:true,platform:'node',format:'esm',write:false,logLevel:'silent',plugins:[{name:'local-finance-boundaries',setup(b){b.onResolve({filter:/.*/},a=>Object.hasOwn(stubs,a.path)?{path:a.path,namespace:'stub'}:null);b.onLoad({filter:/.*/,namespace:'stub'},a=>({contents:stubs[a.path],loader:'js'}))}}]});
 const route=await import('data:text/javascript;base64,'+Buffer.from(output.outputFiles[0].text).toString('base64'));return {route,records,dispose(){delete globalThis[key]}};
}
function req(query='',body,headers={}){const r=new Request('http://127.0.0.1/local'+query,{method:body?'POST':'GET',headers:{'content-type':'application/json',...headers},...(body?{body:JSON.stringify(body)}:{})});r.nextUrl=new URL(r.url);return r}
const path='teams/team/fundraising/fund';const campaign={title:'Local campaign',description:'Fixture',isShareable:true,status:'open',goalAmount:100,currentAmount:12,deadline:'2099-01-01',externalLink:'https://example.invalid/fund',donorEmail:'private@local.test',stripeAccountId:'private-provider-id'};
const query='?teamId=team&fundId=fund';const intent={donorName:'Local Donor',donorEmail:'local@local.test',donorPhone:'5555555555',relationship:'friend',amount:2.34,method:'etransfer'};
test('actual fundraising route exposes an allowlist and persists one pending replay-safe intent without raising confirmed totals',async()=>{const h=await load('public/fundraising',{[path]:campaign});try{const publicBody=await(await h.route.GET(req(query))).json();assert.equal(publicBody.campaign.currentAmount,12);assert.equal(publicBody.campaign.donorEmail,undefined);assert.equal(publicBody.campaign.stripeAccountId,undefined);const key={'idempotency-key':'local_intent_key_0001'};const a=await h.route.POST(req(query,intent,key)),b=await h.route.POST(req(query,intent,key));assert.equal(a.status,200);assert.equal(b.status,200);assert.deepEqual(await a.json(),await b.json());const rows=[...h.records].filter(([p])=>p.includes('/donations/'));assert.equal(rows.length,1);assert.equal(rows[0][1].status,'pending');assert.equal(rows[0][1].amount,2.34);assert.equal(h.records.get(path).currentAmount,12);assert.equal((await h.route.POST(req(query,{...intent,amount:0},key))).status,400);assert.equal((await h.route.GET(req('?teamId=other&fundId=fund'))).status,404)}finally{h.dispose()}});
test('actual fundraising route rejects closed and unshareable campaigns for both read and intent submission',async()=>{for(const state of[{status:'closed'},{isShareable:false},{deadline:'2000-01-01'}]){const h=await load('public/fundraising',{[path]:{...campaign,...state}});try{assert.equal((await h.route.GET(req(query))).status,404);assert.equal((await h.route.POST(req(query,intent,{'idempotency-key':'local_closed_key_001'}))).status,404);assert.equal(h.records.size,1)}finally{h.dispose()}}});
test('actual public donation projection bounds external links and the retired mutation endpoint rejects requests',async()=>{for(const link of['javascript:alert(1)','https://example.invalid/fund']){const h=await load('public/donations',{[path]:{...campaign,externalLink:link}});try{const r=await h.route.GET(req(query));assert.equal(r.status,200);const data=(await r.json()).data;assert.equal(data.donorEmail,undefined);assert.equal(data.stripeAccountId,undefined);assert.equal(data.externalLink,link.startsWith('https:')?link:null);assert.equal((await h.route.POST()).status,410);assert.equal(h.records.size,1)}finally{h.dispose()}}});
test('actual payment-item GET filters inactive items and rejects removed and companion-tenant members without provider access',async()=>{const records={'teams/team':{ownerUserId:'owner'},'teams/team/paymentItems/active':{id:'active',isActive:true,amount:1234},'teams/team/paymentItems/inactive':{id:'inactive',isActive:false},'teams/team/members/removed':{userId:'removed',status:'removed'}};for(const[uid,status]of[['owner',200],['removed',403],['companion',403]]){const h=await load('stripe/payment-items',records,{uid});try{const r=await h.route.GET(req('?teamId=team'));assert.equal(r.status,status);if(status===200)assert.deepEqual((await r.json()).items,[records['teams/team/paymentItems/active']]);assert.equal(h.records.size,4)}finally{h.dispose()}}});
test('actual offline payment handler stores integer cents once and respects infrastructure authorization and input denials',async()=>{const body={teamId:'team',payerName:'Local payer',paymentItemName:'Local fee',amount:1234,currency:'cad',payerEmail:'LOCAL@LOCAL.TEST'};const h=await load('payments/offline',{}, {uid:'owner'});try{const r=await h.route.POST(req('',body));assert.equal(r.status,200);assert.equal(h.records.size,1);const row=[...h.records.values()][0];assert.equal(row.amount,1234);assert.equal(row.currency,'cad');assert.equal(row.payment_method,'offline');assert.equal(row.status,'paid');assert.equal(row.payer_email,'local@local.test');assert.equal(row.recorded_by,'owner');assert.equal((await h.route.POST(req('',{...body,amount:1.2}))).status,400);assert.equal(h.records.size,1)}finally{h.dispose()}const denied=await load('payments/offline',{}, {uid:'companion'}, {allowed:false,status:403,error:'Forbidden'});try{assert.equal((await denied.route.POST(req('',body))).status,403);assert.equal(denied.records.size,0)}finally{denied.dispose()}});
