import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {fileURLToPath} from 'node:url';
import {communicationDb,loadCommunicationRoute} from './helpers/communication-route-harness.mjs';
import {createCompetition} from '../src/lib/competition/document.ts';
import {registrationConfigHash,registrationPaymentSnapshot} from '../src/lib/registration-policy.ts';
const draft=()=>createCompetition({title:'New Cup',registrationFirst:true,teams:[],rules:{version:2,format:'single_elimination',timezone:'UTC'},options:{resources:[{id:'court',name:'Court'}],windows:[{date:'2026-10-01',startTime:'08:00',endTime:'20:00'}],duration:30,rest:10,turnaround:5,maxGamesPerDay:8}});
const event=()=>({isTournament:true,registrationOpen:true,competition:draft(),tournamentGames:[],tournamentTeamsData:[],tournamentTeams:[]});
const request=body=>new Request('http://localhost/api/public/portals/action',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
for(const mode of ['free','offline','stripe'])test(`${mode} signup and acceptance enforce payment eligibility before adding teams`,async()=>{
 const raw={title:'Team signup',type:'team',is_active:true,form_version:1,registration_cost:mode==='free'?'0':'25',currency:'CAD',payment_method:mode,offline_payment_instructions:'Pay organizer',waiver_mode:'none',form_schema:[{id:'name',label:'Coach name',type:'short_text',required:true},{id:'teamName',label:'Team Name',type:'short_text',required:true},{id:'email',label:'Email',type:'email',required:true}]};const config={...raw,config_hash:registrationConfigHash(raw)};
 const {db,records}=communicationDb({'teams/t':{ownerUserId:'owner',planId:'elite'},'teams/t/events/e':event(),'teams/t/events/e/registration/team_config':config},{serializeTransactions:true,enforceReadBeforeWrite:true});const app=await loadCommunicationRoute('../../src/app/api/public/portals/action/route.ts',db,{uid:'owner'});
 try {const response=await app.route.POST(request({kind:'tournament',action:'register',teamId:'t',eventId:'e',protocolId:'team_config',requestId:`registration-${mode}-001`,formVersion:1,formHash:config.config_hash,answers:{name:'Coach Alpha',teamName:'Alpha',email:'alpha@example.test'}}));const body=await response.json();assert.equal(response.status,200,JSON.stringify(body));assert.equal(records.get('teams/t/events/e').competition.topology.teams.length,mode==='free'?1:0);const acceptance=await app.route.POST(request({kind:'tournament',action:'update-registration',teamId:'t',eventId:'e',entryId:body.entryId,status:'accepted'}));assert.equal(acceptance.status,mode==='stripe'?409:200,JSON.stringify(await acceptance.json()));assert.equal(records.get('teams/t/events/e').competition.topology.teams.length,mode==='stripe'?0:1);if(mode==='offline')assert.equal(records.get(`teams/t/events/e/registrationEntries/${body.entryId}`).payment.status,'confirmed');}finally{app.dispose();}
});
async function paymentModule(db){const key=`payment_${crypto.randomUUID()}`;globalThis[key]=db;const built=await build({entryPoints:[fileURLToPath(new URL('../src/lib/server-tournament-registration-payment.ts',import.meta.url))],bundle:true,platform:'node',format:'esm',write:false,plugins:[{name:'payment-boundaries',setup(b){b.onResolve({filter:/^(\.\/|@\/lib\/)(firebase-admin|server-stripe-connect)$/},args=>({path:args.path,namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},args=>({contents:args.path.endsWith('firebase-admin')?`export const adminDb=globalThis[${JSON.stringify(key)}];`:`export const connectAccountOwnsTeam=async(team,account)=>team==='t'&&account==='acct_host';`,loader:'js'}));}}]});return {module:await import(`data:text/javascript;base64,${Buffer.from(built.outputFiles[0].text).toString('base64')}`),dispose:()=>delete globalThis[key]};}
const entry=()=>({answers:{teamName:'Paid team',name:'Coach'},status:'pending',payment:{amount:25,currency:'CAD',mode:'stripe',status:'pending'},checkoutSessionId:'cs_paid',checkoutAccountId:'acct_host'});
const session=()=>({id:'cs_paid',payment_status:'paid',amount_total:2500,currency:'cad',metadata:{kind:'tournament_registration',firebase_team_id:'t',event_id:'e',entry_id:'p'}});
for(const scenario of ['paid','unpaid','wrong account','wrong amount','closed'])test(`Stripe fulfillment: ${scenario}`,async()=>{const data=event();if(scenario==='closed')data.registrationOpen=false;const {db,records}=communicationDb({'teams/t/events/e':data,'teams/t/events/e/registrationEntries/p':entry()},{serializeTransactions:true,enforceReadBeforeWrite:true});const app=await paymentModule(db);try{const checkout=session();if(scenario==='unpaid')checkout.payment_status='unpaid';if(scenario==='wrong amount')checkout.amount_total=1;const fulfill=()=>app.module.fulfillTournamentRegistration(checkout,scenario==='wrong account'?'acct_other':'acct_host');if(scenario.startsWith('wrong')){await assert.rejects(fulfill);assert.equal(records.get('teams/t/events/e').competition.topology.teams.length,0);}else{await fulfill();await fulfill();assert.equal(records.get('teams/t/events/e').competition.topology.teams.length,scenario==='paid'?1:0);assert.equal([...records.keys()].filter(k=>k.includes('/payments/')).length,scenario==='unpaid'?0:1);if(scenario==='closed')assert.equal(records.get('teams/t/events/e/registrationEntries/p').enrollment_status,'paid_after_registration_closed');}}finally{app.dispose();}});
test('Stripe fee validation rejects unsupported decimal precision and currency',()=>{assert.throws(()=>registrationPaymentSnapshot({registration_cost:'2.001',currency:'CAD',payment_method:'stripe'}),/decimal/);assert.throws(()=>registrationPaymentSnapshot({registration_cost:'200',currency:'JPY',payment_method:'stripe'}),/CAD/);});
test('checkout validates receipt ownership, demo isolation and server-owned prices',async()=>{
 const {db,records}=communicationDb({'teams/t':{},'teams/t/events/e':event(),'teams/t/events/e/registrationEntries/p':{...entry(),checkoutSessionId:null,request_id:'receipt-private',protocol_id:'team_config'}});
 const key=`checkout_${crypto.randomUUID()}`;const calls=[];globalThis[key]={db,calls};
 const stubs={
  '@/lib/firebase-admin':`export const adminDb=globalThis[${JSON.stringify(key)}].db;`,
  '@/lib/server-request-guards':`export const enforceUserRateLimit=async()=>null;export const readJsonBodyWithLimit=async r=>r.json();`,
  '@/lib/server-stripe-connect':`export const resolveTeamConnectAccount=async()=>({connectAccountId:'acct_host'});`,
  '@/lib/stripe-client':`export const getStripe=()=>({accounts:{retrieve:async()=>({charges_enabled:true})},checkout:{sessions:{create:async(payload,options)=>{globalThis[${JSON.stringify(key)}].calls.push({payload,options});return {id:'cs_created',url:'https://checkout.stripe.com/test'};},retrieve:async()=>({status:'open',url:'https://checkout.stripe.com/test'})}}});`,
  'next/server':`export class NextResponse extends Response{static json(body,init){return new NextResponse(JSON.stringify(body),init);}}`,
 };
 const built=await build({entryPoints:[fileURLToPath(new URL('../src/app/api/tournaments/registration-checkout/route.ts',import.meta.url))],bundle:true,platform:'node',format:'esm',write:false,plugins:[{name:'checkout-boundaries',setup(b){b.onResolve({filter:/.*/},args=>Object.hasOwn(stubs,args.path)?{path:args.path,namespace:'test'}:null);b.onLoad({filter:/.*/,namespace:'test'},args=>({contents:stubs[args.path],loader:'js'}));}}]});
 try{const route=await import(`data:text/javascript;base64,${Buffer.from(built.outputFiles[0].text).toString('base64')}`);const submit=async(overrides={})=>{const req=request({teamId:'t',eventId:'e',entryId:'p',requestId:'receipt-private',amount:1,...overrides});req.nextUrl=new URL(req.url);return route.POST(req);};assert.equal((await submit({requestId:'wrong'})).status,403);records.set('teams/t',{isDemo:true});assert.equal((await submit()).status,403);records.set('teams/t',{});assert.equal((await submit()).status,200);assert.equal(calls.length,1);assert.equal(calls[0].payload.line_items[0].price_data.unit_amount,2500);assert.equal(calls[0].options.stripeAccount,'acct_host');assert.equal((await submit()).status,200);assert.equal(calls.length,1,'reuses the existing checkout without charging again');}finally{delete globalThis[key];}
});
