"use client";

import React, { useState, useMemo } from 'react';
import { useTeam } from '@/components/providers/team-provider';
import { useFirestore, useCollection, useMemoFirebase } from '@/firebase';
import { collection, query, orderBy } from 'firebase/firestore';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
  ArrowLeft,
  Download,
  CheckCircle2,
  Clock,
  AlertCircle,
  Receipt,
  Calendar,
  Loader2,
  ShieldCheck,
} from 'lucide-react';
import { useRouter } from 'next/navigation';
import { format, parseISO } from 'date-fns';
import { AccessRestricted } from '@/components/layout/AccessRestricted';

const STATUS_CONFIG = {
  paid: { label: 'PAID', icon: CheckCircle2, bg: 'bg-green-500/10', text: 'text-green-600', border: 'border-green-200' },
  pending: { label: 'PENDING', icon: Clock, bg: 'bg-amber-500/10', text: 'text-amber-600', border: 'border-amber-200' },
  overdue: { label: 'OVERDUE', icon: AlertCircle, bg: 'bg-red-500/10', text: 'text-red-600', border: 'border-red-200' },
};

const CATEGORY_COLORS: Record<string, string> = {
  Registration: 'bg-blue-100 text-blue-700',
  Equipment: 'bg-purple-100 text-purple-700',
  'Tournament Entry': 'bg-orange-100 text-orange-700',
  Dues: 'bg-pink-100 text-pink-700',
  Medical: 'bg-teal-100 text-teal-700',
  Other: 'bg-gray-100 text-gray-700',
};

type Payment = {
  id: string;
  childId?: string;
  childName?: string;
  teamId?: string;
  teamName?: string;
  description: string;
  amount: number;
  status: 'paid' | 'pending' | 'overdue';
  date: string;
  dueDate?: string;
  invoiceNumber?: string;
  category?: string;
};

function downloadInvoice(payment: Payment) {
  const date = (() => { try { return format(parseISO(payment.date), 'MMMM d, yyyy'); } catch { return payment.date; } })();
  const dueDate = payment.dueDate ? (() => { try { return format(parseISO(payment.dueDate!), 'MMMM d, yyyy'); } catch { return payment.dueDate; } })() : '—';
  const w = window.open('', '_blank');
  if (w) {
    const invoiceNumber = payment.invoiceNumber || payment.id;
    w.document.title = `Invoice ${invoiceNumber}`;
    w.document.body.replaceChildren();
    w.document.body.style.cssText = 'font-family:sans-serif;padding:40px';

    const addText = (tag: keyof HTMLElementTagNameMap, text: string, style?: string) => {
      const element = w.document.createElement(tag);
      element.textContent = text;
      if (style) element.style.cssText = style;
      w.document.body.appendChild(element);
    };

    addText('h1', 'THESQUAD Invoice');
    addText('p', `Invoice #: ${invoiceNumber}`);
    addText('p', `Date: ${date}`);
    addText('p', `Due: ${dueDate}`);
    w.document.body.appendChild(w.document.createElement('hr'));
    addText('p', payment.description);
    addText('h2', `$${payment.amount.toFixed(2)}`, 'color:#E5283C');
    addText('p', `Status: ${payment.status.toUpperCase()}`);
    addText('footer', 'Generated by TheSquad.pro', 'margin-top:40px;font-size:11px;color:#999');
    setTimeout(() => { w.print(); }, 500);
  }
}

export default function PaymentsPage() {
  const { user, isParent } = useTeam();
  const db = useFirestore();
  const router = useRouter();
  const [filterStatus, setFilterStatus] = useState<'all' | 'paid' | 'pending' | 'overdue'>('all');

  const paymentsQuery = useMemoFirebase(() => {
    if (!db || !user?.id) return null;
    return query(collection(db, 'users', user.id, 'payments'), orderBy('date', 'desc'));
  }, [db, user?.id]);

  const { data: rawPayments, isLoading } = useCollection<Payment>(paymentsQuery);

  const payments = useMemo(() => rawPayments || [], [rawPayments]);

  const stats = useMemo(() => {
    const paid = payments.filter(p => p.status === 'paid').reduce((s, p) => s + p.amount, 0);
    const outstanding = payments.filter(p => p.status !== 'paid').reduce((s, p) => s + p.amount, 0);
    const overdue = payments.filter(p => p.status === 'overdue').reduce((s, p) => s + p.amount, 0);
    const nextDue = payments
      .filter(p => p.status === 'pending' && p.dueDate)
      .sort((a, b) => a.dueDate!.localeCompare(b.dueDate!))
      .at(0);
    return { paid, outstanding, overdue, nextDue };
  }, [payments]);

  const filtered = useMemo(() => {
    if (filterStatus === 'all') return payments;
    return payments.filter(p => p.status === filterStatus);
  }, [payments, filterStatus]);

  if (!isParent) return <AccessRestricted type="role" title="Guardian Access Required" description="Payment records are only accessible to guardians." />;

  return (
    <div className="space-y-10 pb-20 animate-in fade-in duration-700">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="icon" className="rounded-2xl h-10 w-10 hover:bg-primary/5" onClick={() => router.push('/family')}>
            <ArrowLeft className="h-5 w-5" />
          </Button>
          <div className="space-y-1">
            <Badge className="bg-primary/10 text-primary border-none font-black uppercase tracking-widest text-[9px] h-6 px-3">Household Finance</Badge>
            <h1 className="text-4xl md:text-5xl font-black tracking-tighter uppercase leading-none text-foreground">Payment Hub</h1>
            <p className="text-muted-foreground font-bold uppercase tracking-[0.2em] text-[10px] ml-1">Full financial record for your household</p>
          </div>
        </div>
      </div>

      {/* Stats Row */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <Card className="rounded-[2rem] border-none shadow-xl bg-black text-white overflow-hidden">
          <CardContent className="p-6">
            <div className="flex items-center justify-between mb-3">
              <div className="bg-green-500/20 p-2 rounded-xl"><CheckCircle2 className="h-5 w-5 text-green-400" /></div>
              <Badge className="bg-white/10 text-white border-none font-black text-[8px] uppercase">YTD</Badge>
            </div>
            <p className="text-[9px] font-black uppercase tracking-widest opacity-50 mb-1">Total Paid</p>
            <p className="text-3xl font-black">${stats.paid.toFixed(2)}</p>
          </CardContent>
        </Card>
        <Card className="rounded-[2rem] border-none shadow-md bg-white ring-1 ring-black/5 overflow-hidden">
          <CardContent className="p-6">
            <div className="mb-3">
              <div className="bg-amber-500/10 p-2 rounded-xl w-fit"><Clock className="h-5 w-5 text-amber-500" /></div>
            </div>
            <p className="text-[9px] font-black uppercase tracking-widest opacity-50 mb-1">Outstanding</p>
            <p className="text-3xl font-black text-amber-600">${stats.outstanding.toFixed(2)}</p>
          </CardContent>
        </Card>
        <Card className="rounded-[2rem] border-none shadow-md bg-white ring-1 ring-black/5 overflow-hidden">
          <CardContent className="p-6">
            <div className="mb-3">
              <div className="bg-red-500/10 p-2 rounded-xl w-fit"><AlertCircle className="h-5 w-5 text-red-500" /></div>
            </div>
            <p className="text-[9px] font-black uppercase tracking-widest opacity-50 mb-1">Overdue</p>
            <p className="text-3xl font-black text-red-600">${stats.overdue.toFixed(2)}</p>
          </CardContent>
        </Card>
        <Card className="rounded-[2rem] border-none shadow-md bg-white ring-1 ring-black/5 overflow-hidden">
          <CardContent className="p-6">
            <div className="mb-3">
              <div className="bg-primary/10 p-2 rounded-xl w-fit"><Calendar className="h-5 w-5 text-primary" /></div>
            </div>
            <p className="text-[9px] font-black uppercase tracking-widest opacity-50 mb-1">Next Due</p>
            <p className="text-lg font-black">
              {stats.nextDue?.dueDate ? (() => { try { return format(parseISO(stats.nextDue.dueDate), 'MMM d'); } catch { return '—'; } })() : '—'}
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Filter Tabs */}
      <div className="flex items-center gap-2 flex-wrap">
        {(['all', 'paid', 'pending', 'overdue'] as const).map(s => (
          <button
            key={s}
            onClick={() => setFilterStatus(s)}
            className={`px-5 h-9 rounded-2xl text-[10px] font-black uppercase tracking-widest transition-all border-2 ${
              filterStatus === s
                ? 'bg-primary text-white border-primary shadow-md shadow-primary/20'
                : 'bg-white text-muted-foreground border-black/5 hover:border-primary/20'
            }`}
          >
            {s === 'all' ? `All (${payments.length})` : s}
          </button>
        ))}
      </div>

      {/* Payment List */}
      {isLoading ? (
        <div className="flex items-center justify-center h-40 gap-3">
          <Loader2 className="h-8 w-8 animate-spin text-primary" />
          <p className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">Loading records...</p>
        </div>
      ) : filtered.length === 0 ? (
        <Card className="rounded-[3rem] border-4 border-dashed border-muted/30 bg-muted/5">
          <CardContent className="p-16 flex flex-col items-center justify-center text-center">
            <div className="bg-white p-6 rounded-[2rem] shadow-xl mb-6 ring-1 ring-black/5">
              <Receipt className="h-12 w-12 text-primary/30" />
            </div>
            <h3 className="text-2xl font-black uppercase tracking-tight mb-2">No Records Found</h3>
            <p className="text-sm font-bold text-muted-foreground uppercase tracking-widest">
              {filterStatus === 'all' ? 'Payment history will appear here once transactions are recorded.' : `No ${filterStatus} payments found.`}
            </p>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-3">
          {filtered.map(payment => {
            const config = STATUS_CONFIG[payment.status] || STATUS_CONFIG.pending;
            const StatusIcon = config.icon;
            const dateStr = (() => { try { return format(parseISO(payment.date), 'MMM d, yyyy'); } catch { return payment.date; } })();
            const dueDateStr = payment.dueDate ? (() => { try { return format(parseISO(payment.dueDate), 'MMM d, yyyy'); } catch { return payment.dueDate; } })() : null;
            return (
              <Card key={payment.id} className="rounded-[2rem] border-none shadow-md bg-white ring-1 ring-black/5 hover:shadow-lg transition-all hover:-translate-y-0.5 duration-200 overflow-hidden">
                <CardContent className="p-0">
                  <div className="flex items-stretch">
                    <div className={`w-1.5 shrink-0 ${payment.status === 'paid' ? 'bg-green-500' : payment.status === 'overdue' ? 'bg-red-500' : 'bg-amber-400'}`} />
                    <div className="flex-1 p-5 flex items-center gap-4 min-w-0">
                      <div className={`p-3 rounded-2xl shrink-0 ${config.bg}`}>
                        <StatusIcon className={`h-5 w-5 ${config.text}`} />
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 flex-wrap mb-0.5">
                          <h4 className="font-black text-sm uppercase tracking-tight truncate">{payment.description}</h4>
                          {payment.category && (
                            <span className={`text-[8px] font-black uppercase tracking-wide px-2 py-0.5 rounded-full ${CATEGORY_COLORS[payment.category] || CATEGORY_COLORS.Other}`}>
                              {payment.category}
                            </span>
                          )}
                        </div>
                        <div className="flex items-center gap-3 flex-wrap">
                          <p className="text-[10px] font-bold text-muted-foreground">
                            {payment.childName && <span className="text-foreground font-black">{payment.childName} · </span>}
                            {payment.teamName}
                          </p>
                          <span className="text-[10px] text-muted-foreground/50">•</span>
                          <p className="text-[10px] font-bold text-muted-foreground">{dateStr}</p>
                          {dueDateStr && payment.status !== 'paid' && (
                            <><span className="text-[10px] text-muted-foreground/50">•</span>
                            <p className={`text-[10px] font-bold ${payment.status === 'overdue' ? 'text-red-500' : 'text-muted-foreground'}`}>Due {dueDateStr}</p></>
                          )}
                          {payment.invoiceNumber && (
                            <><span className="text-[10px] text-muted-foreground/50">•</span>
                            <p className="text-[10px] font-bold text-muted-foreground/60">#{payment.invoiceNumber}</p></>
                          )}
                        </div>
                      </div>
                      <div className="shrink-0 text-right flex flex-col items-end gap-2">
                        <p className={`text-xl font-black ${payment.status === 'paid' ? 'text-green-600' : payment.status === 'overdue' ? 'text-red-500' : 'text-amber-600'}`}>
                          ${payment.amount.toFixed(2)}
                        </p>
                        <div className="flex items-center gap-2">
                          <Badge className={`border ${config.border} ${config.bg} ${config.text} font-black text-[8px] uppercase tracking-widest border-none`}>
                            {config.label}
                          </Badge>
                          {payment.status === 'paid' && (
                            <Button
                              size="sm"
                              variant="outline"
                              className="h-7 px-3 rounded-xl border-2 text-[9px] font-black uppercase hover:border-primary hover:text-primary"
                              onClick={() => downloadInvoice(payment)}
                            >
                              <Download className="h-3 w-3 mr-1" /> Invoice
                            </Button>
                          )}
                        </div>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>
      )}

      {/* Security Footer */}
      <Card className="rounded-[2rem] border-none shadow-md bg-black text-white overflow-hidden">
        <CardContent className="p-6 flex items-center gap-4">
          <div className="bg-white/10 p-3 rounded-2xl shrink-0"><ShieldCheck className="h-6 w-6 text-primary" /></div>
          <div>
            <p className="text-[10px] font-black uppercase tracking-widest opacity-60">Secure Record</p>
            <p className="text-xs font-bold text-white/80">All financial records are encrypted and stored securely. Download invoices for your personal records.</p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
