"use client";
import { useCallback, useEffect, useRef, useState } from 'react';
import { Pause, Play, RotateCcw, Volume2, VolumeX, X } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import GameCanvas from './GameCanvas';
import { DIFFICULTY, SPORTS, STORAGE, normalizeDifficulty, normalizeSport, storageGet, storageSet, type Difficulty, type Sport } from './game-core';

type ScoreState = { player: number; opponent: number; status: string; over: boolean; pitches?: number; distance?: number };
export default function TimeOutModal({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) {
  const [sport,setSport]=useState<Sport>('soccer'); const [difficulty,setDifficulty]=useState<Difficulty>('easy'); const [paused,setPaused]=useState(false); const [sound,setSound]=useState(false); const [score,setScore]=useState<ScoreState>({player:0,opponent:0,status:'KICK OFF',over:false}); const api=useRef<{action:()=>void;reset:()=>void}|null>(null);
  useEffect(()=>{setSport(normalizeSport(storageGet(STORAGE.sport,'soccer')));setDifficulty(normalizeDifficulty(storageGet(STORAGE.difficulty,'easy')));setSound(storageGet(STORAGE.sound,'false')==='true')},[]);
  useEffect(()=>{const v=()=>setPaused(true); document.addEventListener('visibilitychange',v); return()=>document.removeEventListener('visibilitychange',v)},[]);
  const chooseSport=(v:Sport)=>{setSport(v);storageSet(STORAGE.sport,v);setPaused(false)}; const chooseDifficulty=(v:Difficulty)=>{setDifficulty(v);storageSet(STORAGE.difficulty,v);setPaused(false)};
  const setAudio=(v:boolean)=>{setSound(v);storageSet(STORAGE.sound,String(v))}; const sportInfo=SPORTS.find(x=>x.id===sport)!;
  const onReady=useCallback((next:{action:()=>void;reset:()=>void})=>{api.current=next},[]);
  const handleScore = useCallback((next: ScoreState) => { setScore(next); if (sport === 'baseball' && next.distance) { const previous = Number(storageGet(STORAGE.baseballBest, '0')); if (next.distance > previous) storageSet(STORAGE.baseballBest, String(next.distance)); } }, [sport]);
  const mobileKey = (key: string, pressed: boolean) => window.dispatchEvent(new KeyboardEvent(pressed ? 'keydown' : 'keyup', { key }));
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent hideClose className="sm:max-w-[880px] sm:h-[min(92dvh,820px)] border-2 border-foreground rounded-none sm:rounded-2xl"><div className="bg-secondary text-white px-4 py-3 flex items-center justify-between shrink-0"><div><DialogTitle className="font-mono text-xl font-black tracking-[.16em]">TIME OUT</DialogTitle><p className="text-[10px] tracking-[.2em] text-white/65">ARCADE BREAK · FIRST TO 5</p></div><Button variant="ghost" size="icon" aria-label="Close Time Out" onClick={()=>onOpenChange(false)} className="text-white hover:bg-white/15 hover:text-white"><X /></Button></div>
    <div className="p-3 sm:p-5 space-y-3 overflow-y-auto"><div className="flex gap-2 overflow-x-auto pb-1" aria-label="Select sport">{SPORTS.map(item=><button key={item.id} onClick={()=>chooseSport(item.id)} className={`min-w-[78px] border-2 p-2 rounded-lg text-center focus-visible:outline focus-visible:outline-4 focus-visible:outline-primary ${sport===item.id?'border-primary bg-primary/10':'border-muted hover:border-foreground/30'}`}><span className="text-xl block">{item.icon}</span><span className="text-[9px] font-black uppercase tracking-wide">{item.label}</span></button>)}</div>
      <div className="flex flex-wrap gap-2 items-center"><span className="text-[10px] font-black uppercase tracking-widest text-muted-foreground mr-1">Difficulty</span>{(Object.keys(DIFFICULTY) as Difficulty[]).map(item=><button key={item} onClick={()=>chooseDifficulty(item)} className={`px-3 py-1.5 border-2 rounded-md text-[10px] font-black uppercase tracking-widest ${difficulty===item?'border-primary bg-primary text-white':'border-muted hover:border-primary'}`}>{DIFFICULTY[item].label}</button>)}<span className="ml-auto font-mono text-xs font-black">YOU {score.player} — {score.opponent} CPU {score.pitches !== undefined && ` · ${score.pitches} PITCHES`}</span></div>
      <div className="border-2 border-foreground shadow-[5px_5px_0px_hsl(var(--primary))]"><GameCanvas sport={sport} difficulty={difficulty} paused={paused} sound={sound} onReady={onReady} onScore={handleScore}/></div>
      <div className="flex flex-col sm:flex-row gap-3 sm:items-center"><p className="flex-1 text-xs leading-relaxed"><strong className="uppercase">How to play:</strong> {sportInfo.instructions} {score.status && <span className="text-primary font-black" aria-live="polite"> {score.status}</span>}</p><div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>setPaused(!paused)} aria-label={paused?'Resume game':'Pause game'}>{paused?<Play/>:<Pause/>}{paused?'Resume':'Pause'}</Button><Button variant="outline" size="sm" onClick={()=>api.current?.reset()} aria-label="Restart game"><RotateCcw/>Restart</Button><Button variant="outline" size="sm" onClick={()=>setAudio(!sound)} aria-label={sound?'Mute sound':'Enable sound'}>{sound?<Volume2/>:<VolumeX/>}</Button></div></div>
      <div className="grid grid-cols-3 gap-2 sm:hidden touch-none" aria-label="Touch controls"><span /><button aria-label="Move up" onPointerDown={e=>{e.preventDefault();mobileKey('ArrowUp',true)}} onPointerUp={()=>mobileKey('ArrowUp',false)} onPointerCancel={()=>mobileKey('ArrowUp',false)} className="rounded bg-muted py-3">↑</button><span /><button aria-label="Move left" onPointerDown={e=>{e.preventDefault();mobileKey('ArrowLeft',true)}} onPointerUp={()=>mobileKey('ArrowLeft',false)} onPointerCancel={()=>mobileKey('ArrowLeft',false)} className="rounded bg-muted py-3">←</button><button aria-label="Game action" onPointerDown={e=>{e.preventDefault();api.current?.action()}} className="rounded bg-primary py-3 text-[10px] text-white font-black">ACTION</button><button aria-label="Move right" onPointerDown={e=>{e.preventDefault();mobileKey('ArrowRight',true)}} onPointerUp={()=>mobileKey('ArrowRight',false)} onPointerCancel={()=>mobileKey('ArrowRight',false)} className="rounded bg-muted py-3">→</button><span /><button aria-label="Move down" onPointerDown={e=>{e.preventDefault();mobileKey('ArrowDown',true)}} onPointerUp={()=>mobileKey('ArrowDown',false)} onPointerCancel={()=>mobileKey('ArrowDown',false)} className="rounded bg-muted py-3">↓</button><span /></div><p className="text-[10px] text-muted-foreground">Desktop: WASD or arrows to move · Space to act · R to restart. Sound starts muted.</p></div></DialogContent></Dialog>;
}
